# Generated by Django 5.0 on 2024-08-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0004_alter_comment_user_alter_like_user_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
